# Site
repository: shamelessplug.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mark D Rushton
title: Director of Software Engineering
email: mark@rushtonmd.com
website: rushtonmd.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  rushtonmd
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: rushtonmd
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/cartoon-profile-photo-jan-2024-2.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a father, project manager and problem solver living in sunny San Diego. My trajectory has taken me from developer to project manager and back again a multitude of times. My greatest successes emerge when solving complex problems and leading teams to create amazing things. If I'm surrounded by inspired and funny people who are passionate about solving problems, I'm a happy camper.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GitHub
        link: gitub.com
        # link_text: github.com
        sub_title: Director of Software Engineering
        caption: April 2021 - Present
        quote: >
          Built a team from the ground up with the prime directive of deprecating old friends and building amazing products.
        description: | # this will include new lines to allow paragraphs
            My team was soely responsible for delivering extremely popular features such as math rendering in github, and the ability to render mermaid diagrams. Along with these features, we embarked on a 2 year project to deprecated a neglected service that had more security vulnerabilties than a sticky note with passwords on it. 

            Currently my team is embedded in the Copilot organization, enabling user management and billing capabilities to businesses and individuals wanting to use the cornucopia of AI products we offer.  
      - layout: left
        title: GitHub
        link: gitub.com
        # link_text: github.com
        sub_title: Director of Technical Program Management
        caption: May 2016 - April 2021
        quote: >
          Managed a team of fantastic Technical Project Managers.
        description: | # this will include new lines to allow paragraphs
            My team was soely responsible for delivering extremely popular features such as math rendering in github, and the ability to render mermaid diagrams. Along with these features, we embarked on a 2 year project to deprecated a neglected service that had more security vulnerabilties than a sticky note with passwords on it. 

            Currently my team is embedded in the Copilot organization, enabling user management and billing capabilities to businesses and individuals wanting to use the cornucopia of AI products we offer.  
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Missouri University of Science and Technology
        sub_title: Master of Science, Systems Engineering
        link: mst.edu
      - layout: top-middle
        title: Missouri State University
        sub_title: Bachelor of Science, Mathematics and Computer Science
        link: missouristate.edu
        
  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: Missouri University of Science and Technology
        sub_title: Master of Science, Systems Engineering
        link: mst.edu
      - layout: top-middle
        title: Missouri State University
        sub_title: Bachelor of Science, Mathematics and Computer Science
        link: missouristate.edu
        
  - title: Other Fun Stuff
    layout: list
    content: |
      fun things

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
