# Site
repository: shamelessplug.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mark D Rushton
title: Director of Software Engineering
email: mark@rushtonmd.com
website: rushtonmd.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  rushtonmd
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: rushtonmd
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: another link
  icon: fa fa-file-pdf
  url: rushtonmd.com/files/rushton_resume_2023.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/cartoon-profile-photo-jan-2024-2.jpg
about_content: | # this will include new lines to allow paragraphs
  I am battle-scarred project and engineering manager living in sunny San Diego Californnia. My path has woven back and forth between being a developer and manager multiple times. My most noteworthy accomplishments arise from unraveling complex issues and guiding teams to forge remarkable creations. I am most content when surrounded by enthusiastic and witty people, driven by a strong passion for solving problems — that's when I'm truly in my element.

  <br>
  
  **Some neato stuff I dun did:** 
  
  [Built a 1965 Rambler American](https://jzrambler.com/2022/10/04/sold.html)
  
  [Converted a 1988 Suzuki Samurai to Electric (EV)](https://rushtonmd.github.io/88evsamurai.github.io/) 
  
  [Did some hiking](https://www.alltrails.com/members/mark-rushton-20) 
  
content:
  - title: Current Positions 
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GitHub
        link: github.com
        sub_title: Director of Software Engineering
        caption: April 2021 - Present
        quote: >
          Built a team from the ground up with the prime directive of deprecating old friends and building amazing products.
        description: | # this will include new lines to allow paragraphs
            My team was soely responsible for delivering extremely popular features such as math rendering in github, and the ability to render mermaid diagrams. Along with these features, we embarked on a 2 year project to deprecated a neglected service that had more security vulnerabilties than a sticky note with passwords on it. 

            Currently my team is embedded in the Copilot organization, enabling user management and billing capabilities to businesses and individuals wanting to use the cornucopia of AI products we offer.  
      - layout: left
        title: University of San Diego Extension
        link: extendedstudies.ucsd.edu
        sub_title: Instructor of Project Management and Agile Courses
        caption: October 2018 - Present
        quote: >
          Courses: Project Management Essentials and Agile Power Practices
        description: | # this will include new lines to allow paragraphs
            I'm the instructor for 2 coarses: Project Management Essentials and Agile Power Practices. These courses, depending on the session, are in person, totally online, or a hybrid. Being able to help and connect with professionals and those new to project management allows me to stay connected to the needs of those who are seeking practical and applicable skills. This is an extremely fullfilling and humbling experience to be able to teach these courses.
  
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Missouri University of Science and Technology
        sub_title: Master of Science, Systems Engineering
        link: mst.edu
      - layout: top-middle
        title: Missouri State University
        sub_title: Bachelor of Science, Mathematics and Computer Science
        link: missouristate.edu
      - layout: top-middle
        title: Certifications
        sub_title: PMP, ACP, CSM, CSPO, CSP, ICP-ACC, Six Sigma Green Belt
  
  - title: Prior Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GitHub
        link: github.com
        sub_title: Director of Technical Program Management
        caption: May 2016 - April 2021
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Sungevity
        link: https://en.wikipedia.org/wiki/Sungevity
        link_text: Sungevity - Oakland California
        sub_title: Software Project Manager / Scrum Master
        caption: February 2015 - May 2016
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Sony Mobile
        link: sony.com
        sub_title: Project Manager - Mobile
        caption: October 2013 - February 2015
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: General Things
        link: https://gopro.com/en/us/
        link_text: (acquired by GoPro)
        sub_title: Project Manager / Engineering Manager
        caption: August 2012 - October 2013
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Watts Water Technologies
        link: watts.com
        sub_title: Engineering Manager
        caption: 2007 - 2012
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Robert Half Technology
        link: roberthalf.com
        sub_title: Technical Recruiter
        caption: 2006 - 2007
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Watts Radiant
        link: watts.com
        sub_title: Software Developer / Design Assistant
        caption: 2004 - 2006
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Freelance Consultant, Programmer, AutoCAD
        caption: 2001 - 2004
        quote: >
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Black & Veatch
        link: bv.com
        sub_title: Software Developer / Intern
        caption: 1998 - 2001
        quote: >
        description: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
